---
title: "Open Science: FAQs"
author: "Helen Kettle"
date: "07/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### What is git? 

Git is version control software i.e. it can be used as a way to back
up your work, collaborate with others and to go back to earlier
versions if you need to. The files are kept in repositories ("repos"
to the cool kids!) - the local repo is in your local file storage and
the web-based repo (the 'remote') is hosted on a server, for example
<https://github.com>. The repo on GitHub can be open to the public or
kept private. You may have used GitHub in the past as somewhere to put
your code/data for journal publications but you may not have used it
when developing your work. This page gives some links to more info on
git and a brief overview of how to use it once you have git on your
machine.
See <http://www.bioss.ac.uk/people/helen/OSwebPagesGIT.html> for more details

### Can you use github for storing computer code for referencing in journals?
In most cases you will need to generate a Zenodo code (DOI) for a specific github commit. This takes a snap shot of the repo and archives it at that point. You also get a nice Zenodo badge to tag on to that commit point, and I'd recommend tagging it with a version number which you can refer to in the paper.

### Where is the best place to store data for referencing in journals?

### Can you recommend where to publicly archive my paper? 

